//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Daniel @RootOne
//

import UIKit
import SnapKit
import Material

class ___VARIABLE_productName:identifier___WireFrame: {
	var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?
    
}